#!/bin/sh
# setup-pf.sh - Automate pf (Packet Filter) deployment for Kawakaze
# This script enables and configures pf on FreeBSD for Kawakaze container networking

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Functions
print_info() {
    echo "${GREEN}[INFO]${NC} $1"
}

print_warn() {
    echo "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo "${RED}[ERROR]${NC} $1"
}

check_pf_enabled() {
    if service pf status 2>/dev/null | grep -q "Enabled"; then
        return 0
    else
        return 1
    fi
}

check_pf_running() {
    if pfctl -s info 2>/dev/null | grep -q "Status: Enabled"; then
        return 0
    else
        return 1
    fi
}

enable_pf_at_boot() {
    print_info "Enabling pf at boot..."
    sysrc pf_enable=YES
    print_info "pf enabled at boot"
}

start_pf() {
    print_info "Starting pf..."
    service pf start
    sleep 1
    if check_pf_running; then
        print_info "pf started successfully"
    else
        print_error "Failed to start pf"
        exit 1
    fi
}

create_basic_pf_conf() {
    PF_CONF="/etc/pf.conf"
    PF_CONF_BACKUP="/etc/pf.conf.kawakaze.backup"

    if [ -f "$PF_CONF" ]; then
        print_warn "pf.conf already exists"
        read -p "Create backup and overwrite? (y/N): " confirm
        if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
            print_info "Keeping existing pf.conf"
            return 0
        fi
        cp "$PF_CONF" "$PF_CONF_BACKUP"
        print_info "Backed up existing pf.conf to $PF_CONF_BACKUP"
    fi

    print_info "Creating basic pf.conf for Kawakaze..."

    # Detect external interface
    EXT_IF=$(netstat -rn | grep -E '^(default|0.0.0.0)' | awk '{print $4}' | head -n 1)
    if [ -z "$EXT_IF" ]; then
        print_warn "Could not detect external interface, using vtnet0"
        EXT_IF="vtnet0"
    fi

    cat > "$PF_CONF" << EOF
# Basic pf.conf for Kawakaze
# Auto-generated by setup-pf.sh

ext_if="$EXT_IF"  # External interface

# Allow all traffic on loopback
set skip on lo0

# Allow traffic from Kawakaze containers
# Kawakaze manages its own NAT and port forwarding via anchors
anchor "kawakaze/*"

# Allow SSH (adjust port if needed)
pass in quick on \$ext_if proto tcp to any port 22 keep state

# Default allow outgoing traffic
pass out keep state

# Default deny incoming (block everything else)
block in all
EOF

    print_info "Created pf.conf with external interface: $EXT_IF"
}

show_status() {
    echo ""
    print_info "=== pf Status ==="
    pfctl -s info

    echo ""
    print_info "=== pf NAT Rules ==="
    pfctl -s nat

    echo ""
    print_info "=== Kawakaze NAT Anchor ==="
    pfctl -a kawakaze -s nat 2>/dev/null || echo "No NAT rules in kawakaze anchor"

    echo ""
    print_info "=== Kawakaze Port Forwarding Anchor ==="
    pfctl -a kawakaze_forwarding -s nat 2>/dev/null || echo "No port forwarding rules in kawakaze_forwarding anchor"
}

# Main script
echo "=========================================="
echo "  Kawakaze pf Setup Script"
echo "=========================================="
echo ""

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    print_error "This script must be run as root"
    exit 1
fi

# Step 1: Check current status
print_info "Checking pf status..."
if check_pf_enabled; then
    print_info "pf is already enabled at boot"
else
    print_warn "pf is not enabled at boot"
fi

if check_pf_running; then
    print_info "pf is currently running"
else
    print_warn "pf is not currently running"
fi

echo ""

# Step 2: Enable pf at boot
if ! check_pf_enabled; then
    enable_pf_at_boot
else
    print_info "pf already enabled at boot, skipping..."
fi

echo ""

# Step 3: Start pf if not running
if ! check_pf_running; then
    start_pf
else
    print_info "pf already running, skipping start..."
fi

echo ""

# Step 4: Ask about pf.conf creation
if [ ! -f "/etc/pf.conf" ] || [ "$1" = "--force-pfconf" ]; then
    if [ "$1" != "--force-pfconf" ]; then
        read -p "Create basic pf.conf? (y/N): " confirm
        if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
            create_basic_pf_conf
            print_info "Loading new pf.conf..."
            pfctl -f /etc/pf.conf
        fi
    else
        create_basic_pf_conf
        print_info "Loading new pf.conf..."
        pfctl -f /etc/pf.conf
    fi
else
    print_info "pf.conf exists, skipping creation (use --force-pfconf to overwrite)"
fi

echo ""

# Step 5: Show final status
show_status

echo ""
print_info "=== Setup Complete ==="
echo ""
echo "pf is now configured for Kawakaze."
echo ""
echo "Next steps:"
echo "  1. Start the Kawakaze backend: kawakaze-backend"
echo "  2. Create and run containers: kawakaze run <image>"
echo "  3. Check pf anchors: pfctl -a kawakaze -s rules"
echo ""
